# =====================
# 模板

# =====================
# 文件

file_java_install_media: "install_media/jdk-8u281-linux-x64.rpm"

# =====================
# 文件夹

# =====================
# 路径

# =====================
# 列表

# =====================
# 变量
