# =====================
# MySQL / Handlers
# =====================
# -- 只会在Playbook的所有Task执行完成后才会执行
# -- 并且只会执行一次

# MySQL：启动
# v1
#- name: mysql start
#  service:
#    name: "mysql"
#    state: started

# v2
- name: mysql start
  shell: "service mysql start"
