# =====================
# 任务：目录
# =====================

# 与当前执行不相关的操作系统组需要注释掉
- name: 当前主机所在的Ansible Inventory组
  debug:
    msg: "{{ group_names }}"

- name: 目录创建：操作系统
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items: "{{ list_directory_os }}"

- name: 目录创建：Java
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items: "{{ list_directory_java }}"
  when: "'java' in group_names"

- name: 目录创建：MySQL数据库
  file:
    path: "{{ item }}"
    owner: "{{ mysql_os_user_name }}"
    group: "{{ mysql_os_user_name }}"
    mode: 0755
    state: directory
  with_items: "{{ list_directory_database_mysql }}"
  when: "'mysql' in group_names"

- name: 目录创建：Python
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items: "{{ list_directory_python }}"
  when: "'python' in group_names"

- name: 目录创建：ZooKeeper
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items: "{{ list_directory_zookeeper }}"
  when: "'zookeeper' in group_names"

- name: 目录创建：OceanBase
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items: "{{ list_directory_oceanbase }}"
  when: "'oceanbase' in group_names"
