# =====================
# MySQL / 软件安装
# =====================

# 上传安装介质
- name: 安装：上传安装介质
  unarchive:
    # ---------------
    # 解压后权限
    owner: "{{ mysql_os_user_name }}"
    group: "{{ mysql_os_user_name }}"
    mode: 0755
    # ---------------
    # 解压操作
    # -- 解压文件
    src: "{{ file_mysql_install_media }}"
    # -- 解压目标
    dest: "{{ directory_software_mysql }}"
    # ---------------

# 软链接：MySQL默认程序访问路径
- name: 软链接：MySQL程序访问默认路径
  file:
    owner: "{{ mysql_os_user_name }}"
    group: "{{ mysql_os_user_name }}"
    mode: 0755
    state: link
    src: "{{ path_mysql_install_media }}"
    dest: "{{ path_softlink_mysql_basedir_default }}"

# 设置环境变量
- name: 环境变量：设置
  shell: "echo -e '\n# MySQL Database\nexport PATH={{ path_softlink_mysql_basedir_default }}/bin:$PATH\n' >> /etc/profile"

# 验证环境变量设置
- name: 环境变量：验证
  shell: "source /etc/profile && mysql -V"
  register: mysql_version

# 显示MySQL的版本信息
- name: MySQL：版本
  debug:
    msg: "{{ mysql_version.stdout_lines }}"

# 配置MySQL的Linux系统服务
- name: MySQL：系统服务
  copy:
    backup: yes
    force: yes
    owner: "{{ mysql_os_user_name }}"
    group: "{{ mysql_os_user_name }}"
    mode: 0755
    # 如果【src】指定的路径是远端服务器上的地址，需要打开参数【remote_src】
    remote_src: yes
    src: "{{ path_mysql_file_linux_service_src }}"
    dest: "{{ path_mysql_file_linux_service_dest }}"
