# =====================
# 部署：MySQL
# =====================

# ----------- Linux
- name: Linux
  hosts:
    - mysql
  vars_files:
    - "roles/mysql/vars/main.yml"
  roles:
    - { role: linux }

# ----------- MySQL
- name: MySQL
  hosts:
    - mysql
  vars_files:
    - "roles/linux/vars/main.yml"
  roles:
    - { role: mysql }

# =====================
# Finished
