# =====================
# ZooKeeper / 任务：安装
# =====================

# 上传安装介质
- name: 安装：上传安装介质
  unarchive:
    # ---------------
    # 解压后权限
    owner: root
    group: root
    mode: 0755
    # ---------------
    # 解压操作
    # -- 解压文件
    src: "{{ file_zookeeper_install_media }}"
    # -- 解压目标
    dest: "{{ directory_software_zookeeper }}"
    # ---------------

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 安装方式：二进制包 / Begin

# 将二进制包的解压文件移动到ZooKeeper安装路径
- name: 二进制包解压文件：移动到ZooKeeper软件根目录
  copy:
    backup: yes
    force: yes
    owner: root
    group: root
    mode: 0755
    # 如果【src】指定的路径是远端服务器上的地址，需要打开参数【remote_src】
    remote_src: yes
    src: "{{ directory_software_zookeeper_after_unzip }}"
    dest: "{{ directory_zookeeper_software_base }}"
  when: zookeeper_install_media_type == "binary"

# 软链接：ZooKeeper默认程序访问路径
# -- 只有在二进制包安装的时候，才会涉及这一步
# -- 只有当软件根目录与默认软链接路径不一致的时候，才需要执行这一步，创建软链接
- name: 软链接：ZooKeeper程序访问默认路径
  file:
    owner: root
    group: root
    mode: 0755
    state: link
    src: "{{ directory_zookeeper_software_base_after_unzip }}"
    dest: "{{ path_softlink_zookeeper_basedir_default }}"
  when: zookeeper_install_media_type == "binary" and directory_zookeeper_software_base != path_softlink_zookeeper_basedir_default

# 设置环境变量
- name: 环境变量：设置
  shell: "echo -e '\n# Apache ZooKeeper\nexport ZK_HOME={{ path_softlink_zookeeper_basedir_default }}\nexport PATH=$ZK_HOME/bin:$PATH\n' >> ~/.bash_profile"
  when: zookeeper_install_media_type == "binary"

# ZooKeeper 配置文件
# ZK 要配置完 配置文件后 才可以通过 zkServer.sh 查看版本信息
# -- 否则会报错
- name: 配置文件：conf/zoo.cfg
  template:
    backup: yes
    src: "{{ template_zookeeper_file_config }}"
    dest: "{{ path_zookeeper_file_config }}"
    owner: root
    group: root
    mode: 0755

# 验证环境变量设置
- name: 环境变量：验证
  shell: "source ~/.bash_profile && zkServer.sh version"
  register: os_command_result_zookeeper_version
  when: zookeeper_install_media_type == "binary"

# 显示ZooKeeper的版本信息
- name: ZooKeeper：版本
  debug:
    msg: "{{ os_command_result_zookeeper_version.stdout_lines }}"
  when: zookeeper_install_media_type == "binary"

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 安装方式：二进制包 / Finished

# ====================== 配置

# 创建：myid
- name: 创建：myid
  shell: "echo {{ zookeeper_host_info[zookeeper_myid].myid }} > {{ directory_zookeeper_dataDir }}/myid"
  ignore_errors: yes

# ====================== 启动

# 启动ZooKeeper
- name: ZooKeeper：启动
  shell: "source ~/.bash_profile && zkServer.sh start"
